name: Platform Pipeline

on:
  workflow_call:

env:
  PLATFORM_PATH: platform

jobs:

  context:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout consumer repository
        uses: actions/checkout@v4

      - name: Checkout platform repository
        uses: actions/checkout@v4
        with:
          repository: TasniimCh/Platform-Pipeline
          ref: master
          path: ${{ env.PLATFORM_PATH }}

      - name: Load Context
        run: bash ${{ env.PLATFORM_PATH }}/scripts/load-context.sh


  phase1:
    needs: context
    runs-on: ubuntu-latest

    steps:

      - name: Checkout consumer repository
        uses: actions/checkout@v4

      - name: Checkout platform repository
        uses: actions/checkout@v4
        with:
          repository: TasniimCh/Platform-Pipeline
          ref: master
          path: ${{ env.PLATFORM_PATH }}

      - name: Run Phase 1
        run: bash ${{ env.PLATFORM_PATH }}/scripts/phase1.sh